# Test script for enhanced FridaInterceptor with iOS version bypass
# This script tests attach mode with iOS 17.6.1 spoofing

Write-Host "`n=== Testing Enhanced FridaInterceptor - Attach Mode ===" -ForegroundColor Cyan
Write-Host "Target: DasherApp (PID 1031)" -ForegroundColor Yellow
Write-Host "iOS Version: 17.6.1 spoofing" -ForegroundColor Yellow

# Load the iOS version config
$configPath = ".\config\ios-versions.json"
$iosConfig = Get-Content $configPath -Raw | ConvertFrom-Json
$selectedVersion = $iosConfig.versions.iOS17_6

Write-Host "`nVersion Details:" -ForegroundColor Green
Write-Host "  System Version: $($selectedVersion.systemVersion)"
Write-Host "  CFNetwork: $($selectedVersion.cfNetwork)"
Write-Host "  Darwin: $($selectedVersion.darwin)"
Write-Host "  Build: $($selectedVersion.buildNumber)"

# Generate the bypass script
$templatePath = ".\frida-interception-and-unpinning\ios-version-bypass-template.js"
$template = Get-Content $templatePath -Raw

$script = $template -replace "\{\{VERSION\}\}", $selectedVersion.systemVersion
$script = $script -replace "\{\{CFNETWORK\}\}", $selectedVersion.cfNetwork
$script = $script -replace "\{\{DARWIN\}\}", $selectedVersion.darwin
$script = $script -replace "\{\{BUILD\}\}", $selectedVersion.buildNumber
$script = $script -replace "\{\{PROXY_HOST\}\}", "192.168.50.9"
$script = $script -replace "\{\{PROXY_PORT\}\}", "8000"

$scriptPath = ".\temp-ios-bypass.js"
$script | Out-File -FilePath $scriptPath -Encoding UTF8

Write-Host "`nGenerated bypass script at: $scriptPath" -ForegroundColor Green

# Test with Python Frida attach
Write-Host "`nAttaching to DasherApp with iOS version bypass..." -ForegroundColor Cyan
$pythonCmd = "python frida-attach.py 1031 `"$scriptPath`""
Write-Host "Command: $pythonCmd" -ForegroundColor Gray

# Run the attach command
$process = Start-Process -FilePath "python" -ArgumentList "frida-attach.py", "1031", $scriptPath -NoNewWindow -PassThru -Wait

if ($process.ExitCode -eq 0) {
    Write-Host "`n[SUCCESS] Script attached successfully!" -ForegroundColor Green
    Write-Host "iOS version bypass is now active on DasherApp" -ForegroundColor Green
    Write-Host "The app should now report as iOS $($selectedVersion.systemVersion)" -ForegroundColor Green
} else {
    Write-Host "`n[ERROR] Failed to attach script (exit code: $($process.ExitCode))" -ForegroundColor Red
}

# Cleanup
Remove-Item $scriptPath -ErrorAction SilentlyContinue
Write-Host "`nTest complete." -ForegroundColor Cyan